name: Test Linux x64
on:
    workflow_dispatch:
jobs:
    test-config:
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    curl -L -o ./temp.tgz https://github.com/libffi/libffi/releases/download/v3.4.7/libffi-3.4.7.tar.gz
                    tar -xvzf temp.tgz
                    ls .
                    
